### ISSUE TITLE
2+ instances of mapbox echart layer on the same page doesn't work as expected

### ISSUE THREAD

**Issue by Maqsim** [naivemap/mapbox-gl-layers#5]
Hey. I love this plugin and use it in one of my project.

BUT, I found a bug. When I initialise 2 maps with echart layers the last initialised map work as expected, but previous one is broken. I did some reverse engineering and found that when you initialise the same coordinate system twice it overrides with last initialised one:

Echarts/CoordinateSystemManager (method `register`)
<img width="466" alt="image" src="https://github.com/naivemap/mapbox-gl-layers/assets/1107049/1e626cac-62be-4456-9a0a-10998145aa34">

Demo:
![ezgif com-optimize-2](https://github.com/naivemap/mapbox-gl-layers/assets/1107049/4fca119a-ee3b-4211-958a-194a35127f6e)

See how scatter data stick to one position on first map, while on second map all works fine. It shares the same position (latest initialised instance).

Please let me know what do you think and if you are going to fix that behaviour.
Thanks in advanced 🙏

**Comment by Maqsim** [comment]
@huanglii Any updates on this one?

**Comment by huanglii** [comment]
> @huanglii Any updates on this one?

I tried using different ids but still had the same problem

**Comment by Maqsim** [comment]
Thanks for fixing it 🙏

**Comment by Maqsim** [comment]
Just tested new version and it solved my problem. Thanks again
